Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/AmbiguousOperator:
  # buggy cop
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'
Style/EmptyMethod:
  EnforcedStyle: expanded
AllCops:
  NewCops: disable

require:
  - rubocop-performance
  - rubocop-minitest
